#pragma once
#include <cwchar>

enum class UiLanguage { English = 0, French = 1, Spanish = 2, Russian = 3, Chinese = 4 };

struct UiTranslationRow {
    const wchar_t* en;
    const wchar_t* fr;
    const wchar_t* es;
    const wchar_t* ru;
    const wchar_t* zh;
};

inline const wchar_t* UiLanguageNativeName(UiLanguage language) {
    switch (language) {
    case UiLanguage::French: return L"Français";
    case UiLanguage::Spanish: return L"Español";
    case UiLanguage::Russian: return L"Русский";
    case UiLanguage::Chinese: return L"中文";
    default: return L"English";
    }
}

inline const wchar_t* UiText(UiLanguage language, const wchar_t* english) {
    static const UiTranslationRow rows[] = {
    {L"Discord", L"Discord", L"Discord", L"Discord", L"Discord"},
    {L"Restore backup", L"Restaurer la sauvegarde", L"Restaurar copia", L"Восстановить копию", L"恢复备份"},
    {L"Backup", L"Sauvegarde", L"Copia de seguridad", L"Резервная копия", L"备份"},
    {L"Backup passphrase", L"Phrase secrète de sauvegarde", L"Frase de la copia", L"Пароль резервной копии", L"备份口令"},
    {L"Create local backup", L"Créer une sauvegarde locale", L"Crear copia local", L"Создать локальную копию", L"创建本地备份"},
    {L"Create backup and upload recovery copy", L"Créer une sauvegarde et téléverser une copie de récupération", L"Crear copia y subir una copia de recuperación", L"Создать копию и загрузить копию восстановления", L"创建备份并上传恢复副本"},
    {L"Backup file", L"Fichier de sauvegarde", L"Archivo de copia", L"Файл резервной копии", L"备份文件"},
    {L"Copy backup path", L"Copier le chemin de sauvegarde", L"Copiar ruta de la copia", L"Копировать путь a la copia", L"复制备份路径"},
    {L"Recovery code", L"Code de récupération", L"Código de recuperación", L"Код восстановления", L"恢复代码"},
    {L"Copy recovery code", L"Copier le code de récupération", L"Copiar código de recuperación", L"Копировать код восстановления", L"复制恢复代码"},
    {L"Download recovery backup", L"Télécharger la sauvegarde de récupération", L"Descargar copia de recuperación", L"Скачать резервную копию восстановления", L"下载恢复备份"},
    {L"Recovery status", L"État de la récupération", L"Estado de recuperación", L"Состояние восстановления", L"恢复状态"},
    {L"Wipe network recovery", L"Effacer la récupération réseau", L"Borrar la recuperación de red", L"Удалить сетевую копию восстановления", L"清除网络恢复"},
    {L"Use a backup passphrase of at least 8 characters, without line breaks.", L"Utilisez une phrase secrète d’au moins 8 caractères, sans saut de ligne.", L"Use una frase de al menos 8 caracteres, sin saltos de línea.", L"Используйте пароль длиной не менее 8 символов без переносов строк.", L"请使用至少 8 个字符且不含换行的备份口令。"},
    {L"There is no backup path to copy yet.", L"Aucun chemin de sauvegarde à copier pour le moment.", L"Todavía no hay una ruta de copia para copiar.", L"Путь к резервной копии пока отсутствует.", L"目前没有可复制的路径。"},
    {L"There is no recovery code to copy yet.", L"Aucun code de récupération à copier pour le moment.", L"Todavía no hay un código de recuperación para copiar.", L"Кода восстановления пока нет.", L"目前没有可复制的恢复代码。"},
    {L"Enter a valid VKR1 recovery code first.", L"Saisissez d’abord un code de récupération VKR1 valide.", L"Introduzca primero un código de recuperación VKR1 válido.", L"Сначала введите действительный код восстановления VKR1.", L"请先输入有效的 VKR1 恢复代码。"},
    {L"Could not send the backup request to the backend.", L"Impossible d’envoyer la demande de sauvegarde au backend.", L"No se pudo enviar la solicitud de copia al backend.", L"Не удалось отправить запрос резервного копирования в backend.", L"无法向后端发送备份请求。"},
    {L"Backup creation and recovery upload queued...", L"Création de sauvegarde et téléversement de récupération en file…", L"Creación de copia y carga de recuperación en cola…", L"Создание копии и загрузка восстановления поставлены в очередь…", L"备份创建和恢复上传已排队…"},
    {L"Encrypted backup creation queued...", L"Création de sauvegarde chiffrée en file…", L"Creación de copia cifrada en cola…", L"Создание зашифрованной копии поставлено в очередь…", L"已排队创建加密备份…"},
    {L"Could not send the recovery download request.", L"Impossible d’envoyer la demande de téléchargement de récupération.", L"No se pudo enviar la solicitud de descarga de recuperación.", L"Не удалось отправить запрос на загрузку восстановления.", L"无法发送恢复下载请求。"},
    {L"Recovery backup download queued...", L"Téléchargement de la sauvegarde de récupération en file…", L"Descarga de la copia de recuperación en cola…", L"Загрузка резервной копии восстановления поставлена в очередь…", L"恢复备份下载已排队…"},
    {L"Wipe the current network recovery record? This replaces its data with tombstones.", L"Effacer l’enregistrement de récupération réseau actuel ? Ses données seront remplacées par des tombstones.", L"¿Borrar el registro de recuperación de red actual? Sus datos serán reemplazados por marcadores de eliminación.", L"Удалить текущую запись сетевого восстановления? Данные будут заменены маркерами удаления.", L"清除当前网络恢复记录？其数据将被墓碑标记替换。"},

    {L"Enter the backup passphrase in the Password field, then press Restore backup.", L"Saisissez la phrase secrète de sauvegarde dans le champ Mot de passe, puis appuyez sur Restaurer la sauvegarde.", L"Introduzca la frase de la copia en el campo Contraseña y pulse Restaurar copia.", L"Введите пароль резервной копии в поле пароля и нажмите «Восстановить копию».", L"在密码字段中输入备份口令，然后按“恢复备份”。"},
    {L"Restoring encrypted backup...", L"Restauration de la sauvegarde chiffrée…", L"Restaurando copia cifrada…", L"Восстановление зашифрованной копии…", L"正在恢复加密备份…"},
    {L"Backup restored; log in with the account's original password.", L"Sauvegarde restaurée ; connectez-vous avec le mot de passe d’origine du compte.", L"Copia restaurada; inicie sesión con la contraseña original de la cuenta.", L"Резервная копия восстановлена; войдите с исходным паролем учётной записи.", L"备份已恢复；请使用账户原始密码登录。"},
    {L"Backup restore failed; check the file and backup passphrase.", L"Échec de la restauration ; vérifiez le fichier et la phrase secrète.", L"Error al restaurar; compruebe el archivo y la frase de la copia.", L"Не удалось восстановить; проверьте файл и пароль резервной копии.", L"恢复失败；请检查文件和备份口令。"},
    {L"Could not send the restore request to the backend.", L"Impossible d’envoyer la demande de restauration au backend.", L"No se pudo enviar la solicitud de restauración al backend.", L"Не удалось отправить запрос восстановления серверной части.", L"无法向后端发送恢复请求。"},
    {L"Advanced application management ▸", L"Gestion avancée des applications ▸", L"Administración avanzada de aplicaciones ▸", L"Расширенное управление приложениями ▸", L"高级应用管理 ▸"},
    {L"Advanced application management ▾", L"Gestion avancée des applications ▾", L"Administración avanzada de aplicaciones ▾", L"Расширенное управление приложениями ▾", L"高级应用管理 ▾"},
    {L"VeilKnit Daemon", L"Démon VeilKnit", L"Demonio VeilKnit", L"Демон VeilKnit", L"VeilKnit 守护进程"},
    {L"Add app", L"Ajouter l’application", L"Añadir aplicación", L"Добавить приложение", L"添加应用"},
    {L"All daemon logs", L"Tous les journaux du démon", L"Todos los registros del demonio", L"Все журналы демона", L"所有守护进程日志"},
    {L"All logs", L"Tous les journaux", L"Todos los registros", L"Все журналы", L"所有日志"},
    {L"Always use saved X-button action", L"Toujours utiliser l’action enregistrée du bouton X", L"Usar siempre la acción guardada del botón X", L"Всегда использовать сохранённое действие кнопки X", L"始终使用已保存的关闭按钮操作"},
    {L"Allow checked", L"Autoriser la sélection", L"Permitir marcadas", L"Разрешить отмеченные", L"允许已勾选"},
    {L"Archive", L"Archive", L"Archivo", L"Архив", L"归档"},
    {L"Discovery cache", L"Cache de découverte", L"Caché de descubrimiento", L"Кэш обнаружения", L"发现缓存"},
    {L"Application", L"Application", L"Aplicación", L"Приложение", L"应用程序"},
    {L"Observed applications", L"Applications observées", L"Aplicaciones observadas", L"Обнаруженные приложения", L"已发现的应用"},
    {L"Recent", L"Récent", L"Recientes", L"Недавние", L"近期"},
    {L"Refresh requests", L"Actualiser les demandes", L"Actualizar solicitudes", L"Обновить запросы", L"刷新请求"},
    {L"Refuse checked", L"Refuser la sélection", L"Rechazar marcadas", L"Отклонить отмеченные", L"拒绝已勾选"},
    {L"Refusal reason", L"Motif du refus", L"Motivo del rechazo", L"Причина отказа", L"拒绝原因"},
    {L"Request", L"Demande", L"Solicitud", L"Запрос", L"请求"},
    {L"Verified headers", L"En-têtes vérifiés", L"Encabezados verificados", L"Проверенные заголовки", L"已验证标头"},
    {L"Application id", L"Identifiant d’application", L"Id. de aplicación", L"Идентификатор приложения", L"应用程序 ID"},
    {L"Application log", L"Journal d’applications", L"Registro de aplicaciones", L"Журнал приложений", L"应用程序日志"},
    {L"Applications", L"Applications", L"Aplicaciones", L"Приложения", L"应用程序"},
    {L"Apply and save walk settings", L"Appliquer et enregistrer les paramètres", L"Aplicar y guardar ajustes", L"Применить и сохранить настройки", L"应用并保存遍历设置"},
    {L"Apply settings", L"Appliquer", L"Aplicar ajustes", L"Применить", L"应用设置"},
    {L"Approve", L"Approuver", L"Aprobar", L"Одобрить", L"批准"},
    {L"Authenticated; starting network services...", L"Authentifié ; démarrage des services réseau…", L"Autenticado; iniciando servicios de red…", L"Проверка пройдена; запуск сетевых служб…", L"已认证；正在启动网络服务…"},
    {L"Authentication failed; correct the details and try again.", L"Échec de l’authentification ; corrigez les informations et réessayez.", L"Error de autenticación; corrija los datos e inténtelo de nuevo.", L"Ошибка входа; исправьте данные и повторите попытку.", L"认证失败；请更正信息后重试。"},
    {L"Backend started; authenticating...", L"Backend démarré ; authentification…", L"Backend iniciado; autenticando…", L"Backend запущен; проверка…", L"后端已启动；正在认证…"},
    {L"Cancel", L"Annuler", L"Cancelar", L"Отмена", L"取消"},
    {L"Check approval", L"Vérifier l’approbation", L"Comprobar aprobación", L"Проверить одобрение", L"检查批准"},
    {L"Check status", L"Vérifier l’état", L"Comprobar estado", L"Проверить состояние", L"检查状态"},
    {L"Chinese", L"Chinois", L"Chino", L"Китайский", L"中文"},
    {L"Close", L"Fermer", L"Cerrar", L"Закрыть", L"关闭"},
    {L"Close properly", L"Fermer proprement", L"Cerrar correctamente", L"Корректно закрыть", L"正确关闭"},
    {L"Compose", L"Rédiger", L"Redactar", L"Написать", L"撰写"},
    {L"Contact nickname", L"Surnom du contact", L"Apodo del contacto", L"Псевдоним контакта", L"联系人昵称"},
    {L"Contacts", L"Contacts", L"Contactos", L"Контакты", L"联系人"},
    {L"Copy key", L"Copier la clé", L"Copiar clave", L"Копировать ключ", L"复制密钥"},
    {L"Copy mailbox header", L"Copier l’en-tête de boîte", L"Copiar encabezado del buzón", L"Копировать заголовок почты", L"复制邮箱标头"},
    {L"Copy main header", L"Copier l’en-tête principal", L"Copiar encabezado principal", L"Копировать основной заголовок", L"复制主标头"},
    {L"Create DHT", L"Créer la DHT", L"Crear DHT", L"Создать DHT", L"创建 DHT"},
    {L"Create account", L"Créer un compte", L"Crear cuenta", L"Создать учётную запись", L"创建账户"},
    {L"Create owned DHT", L"Créer une DHT possédée", L"Crear DHT propia", L"Создать собственную DHT", L"创建自有 DHT"},
    {L"DHT log", L"Journal DHT", L"Registro DHT", L"Журнал DHT", L"DHT 日志"},
    {L"DHT name", L"Nom de la DHT", L"Nombre de DHT", L"Имя DHT", L"DHT 名称"},
    {L"Daemon", L"Démon", L"Demonio", L"Демон", L"守护进程"},
    {L"Daemon status", L"État du démon", L"Estado del demonio", L"Состояние демона", L"守护进程状态"},
    {L"Delete", L"Supprimer", L"Eliminar", L"Удалить", L"删除"},
    {L"Display name", L"Nom affiché", L"Nombre mostrado", L"Отображаемое имя", L"显示名称"},
    {L"English", L"Anglais", L"Inglés", L"Английский", L"英语"},
    {L"Enter a password without line breaks.", L"Saisissez un mot de passe sans saut de ligne.", L"Introduzca una contraseña sin saltos de línea.", L"Введите пароль без переносов строк.", L"请输入不含换行符的密码。"},
    {L"Establish", L"Établir", L"Establecer", L"Установить", L"建立"},
    {L"Establish handshake", L"Établir la connexion", L"Establecer enlace", L"Установить рукопожатие", L"建立握手"},
    {L"External DHT", L"DHT externe", L"DHT externa", L"Внешняя DHT", L"外部 DHT"},
    {L"External VLD0 key", L"Clé VLD0 externe", L"Clave VLD0 externa", L"Внешний ключ VLD0", L"外部 VLD0 密钥"},
    {L"Find mail", L"Chercher le courrier", L"Buscar correo", L"Найти почту", L"查找邮件"},
    {L"Flush", L"Vider", L"Vaciar", L"Сбросить", L"清空"},
    {L"French", L"Français", L"Francés", L"Французский", L"法语"},
    {L"Getting started:\n\n1. Enter your username and password, then press Enter to log in.\n2. Applications request permission through the Applications tab.\n3. Look for a line such as:\n   [api] Application authorization requested: #1 veilknit.rooms\n\nThe important value is the request number (#1 in this example). Enter 1 in Request id and choose Approve.\n\nThe Network tab contains separate adaptive settings and manual start buttons for normal and mail walks. The Headers tab reads and displays your published subkey 0 presence header and subkey 2 mailbox advertisement.\n\nGreen status means ready, orange means starting or reconnecting, and red means stopped or failed.", L"Pour commencer :\n\n1. Saisissez votre nom d’utilisateur et votre mot de passe, puis appuyez sur Entrée.\n2. Les applications demandent une autorisation dans l’onglet Applications.\n3. Cherchez une ligne comme :\n   [api] Application authorization requested: #1 veilknit.rooms\n\nLa valeur importante est le numéro de demande (#1 dans cet exemple). Saisissez 1 dans Identifiant de demande et choisissez Approuver.\n\nL’onglet Réseau contient des réglages adaptatifs et des boutons distincts pour les parcours normal et courrier. L’onglet En-têtes affiche vos en-têtes publiés de présence (sous-clé 0) et de boîte aux lettres (sous-clé 2).\n\nVert signifie prêt, orange signifie démarrage ou reconnexion, rouge signifie arrêté ou en échec.", L"Primeros pasos:\n\n1. Introduzca su nombre de usuario y contraseña y pulse Entrar.\n2. Las aplicaciones solicitan permiso en la pestaña Aplicaciones.\n3. Busque una línea como:\n   [api] Application authorization requested: #1 veilknit.rooms\n\nEl valor importante es el número de solicitud (#1 en este ejemplo). Escriba 1 en Id. de solicitud y elija Aprobar.\n\nLa pestaña Red tiene ajustes adaptativos y botones separados para recorridos normales y de correo. Encabezados muestra los encabezados publicados de presencia (subclave 0) y buzón (subclave 2).\n\nVerde significa listo, naranja significa iniciando o reconectando y rojo significa detenido o con error.", L"Начало работы:\n\n1. Введите имя пользователя и пароль, затем нажмите Войти.\n2. Приложения запрашивают разрешение на вкладке Приложения.\n3. Найдите строку вида:\n   [api] Application authorization requested: #1 veilknit.rooms\n\nВажное значение — номер запроса (#1 в примере). Введите 1 в поле Номер запроса и выберите Одобрить.\n\nНа вкладке Сеть находятся отдельные адаптивные настройки и кнопки обычного и почтового обхода. Вкладка Заголовки показывает опубликованные заголовки присутствия (подключ 0) и почтового ящика (подключ 2).\n\nЗелёный означает готовность, оранжевый — запуск или переподключение, красный — остановку или ошибку.", L"入门：\n\n1. 输入用户名和密码，然后按“登录”。\n2. 应用程序会通过“应用程序”选项卡请求权限。\n3. 查找类似以下内容的行：\n   [api] Application authorization requested: #1 veilknit.rooms\n\n重要的是请求编号（本例为 #1）。在“请求 ID”中输入 1，然后选择“批准”。\n\n“网络”选项卡为普通遍历和邮件遍历提供独立的自适应设置与手动启动按钮。“标头”选项卡显示已发布的在线状态标头（子键 0）和邮箱公告（子键 2）。\n\n绿色表示已就绪，橙色表示正在启动或重新连接，红色表示已停止或失败。"},
    {L"Got it", L"Compris", L"Entendido", L"Понятно", L"知道了"},
    {L"Handshake", L"Poignée de main", L"Enlace", L"Рукопожатие", L"握手"},
    {L"Handshake log", L"Journal de connexion", L"Registro de enlace", L"Журнал рукопожатия", L"握手日志"},
    {L"Header log", L"Journal d’en-têtes", L"Registro de encabezados", L"Журнал заголовков", L"标头日志"},
    {L"Headers", L"En-têtes", L"Encabezados", L"Заголовки", L"标头"},
    {L"Help", L"Aide", L"Ayuda", L"Справка", L"帮助"},
    {L"Inbox", L"Boîte de réception", L"Bandeja de entrada", L"Входящие", L"收件箱"},
    {L"Index", L"Index", L"Índice", L"Индекс", L"索引"},
    {L"Inspect", L"Inspecter", L"Inspeccionar", L"Проверить", L"检查"},
    {L"Language", L"Langue", L"Idioma", L"Язык", L"语言"},
    {L"List", L"Lister", L"Listar", L"Список", L"列表"},
    {L"List apps", L"Lister les applications", L"Listar aplicaciones", L"Список приложений", L"列出应用"},
    {L"List inbox", L"Lister la boîte de réception", L"Listar bandeja de entrada", L"Показать входящие", L"列出收件箱"},
    {L"Local applications", L"Applications locales", L"Aplicaciones locales", L"Локальные приложения", L"本地应用程序"},
    {L"Log in", L"Se connecter", L"Iniciar sesión", L"Войти", L"登录"},
    {L"Login", L"Connexion", L"Entrar", L"Войти", L"登录"},
    {L"Mail mode", L"Mode courrier", L"Modo correo", L"Почтовый режим", L"邮件模式"},
    {L"Mail walking mode", L"Mode de parcours du courrier", L"Modo de recorrido de correo", L"Почтовый режим обхода", L"邮件遍历模式"},
    {L"Mailbox", L"Boîte aux lettres", L"Buzón", L"Почтовый ящик", L"邮箱"},
    {L"Mailbox log", L"Journal de boîte aux lettres", L"Registro del buzón", L"Почтовый журнал", L"邮箱日志"},
    {L"Mailer authorization required", L"Autorisation de la messagerie requise", L"Se requiere autorización del correo", L"Требуется авторизация почты", L"需要邮件应用授权"},
    {L"Main DHT key", L"Clé DHT principale", L"Clave DHT principal", L"Основной ключ DHT", L"主 DHT 密钥"},
    {L"Main key", L"Clé principale", L"Clave principal", L"Основной ключ", L"主密钥"},
    {L"Max hops", L"Sauts max.", L"Saltos máx.", L"Макс. переходов", L"最大跳数"},
    {L"Max sec", L"Sec. max.", L"Seg. máx.", L"Макс. сек.", L"最大秒数"},
    {L"Maximum hops", L"Sauts maximum", L"Saltos máximos", L"Максимум переходов", L"最大跳数"},
    {L"Maximum interval (seconds)", L"Intervalle maximum (secondes)", L"Intervalo máximo (segundos)", L"Максимальный интервал (секунды)", L"最大间隔（秒）"},
    {L"Message", L"Message", L"Mensaje", L"Сообщение", L"消息"},
    {L"Min hops", L"Sauts min.", L"Saltos mín.", L"Мин. переходов", L"最少跳数"},
    {L"Min sec", L"Sec. min.", L"Seg. mín.", L"Мин. сек.", L"最小秒数"},
    {L"Minimize to notification area", L"Réduire dans la zone de notification", L"Minimizar al área de notificación", L"Свернуть в область уведомлений", L"最小化到通知区域"},
    {L"Minimum hops", L"Sauts minimum", L"Saltos mínimos", L"Минимум переходов", L"最少跳数"},
    {L"Minimum interval (seconds)", L"Intervalle minimum (secondes)", L"Intervalo mínimo (segundos)", L"Минимальный интервал (секунды)", L"最小间隔（秒）"},
    {L"Name", L"Nom", L"Nombre", L"Имя", L"名称"},
    {L"Network", L"Réseau", L"Red", L"Сеть", L"网络"},
    {L"Network log", L"Journal réseau", L"Registro de red", L"Сетевой журнал", L"网络日志"},
    {L"Network services are ready.", L"Les services réseau sont prêts.", L"Los servicios de red están listos.", L"Сетевые службы готовы.", L"网络服务已就绪。"},
    {L"Nickname", L"Surnom", L"Apodo", L"Псевдоним", L"昵称"},
    {L"No handshake action requested yet.", L"Aucune action de connexion demandée.", L"Aún no se solicitó una acción de enlace.", L"Действие рукопожатия ещё не запрошено.", L"尚未请求握手操作。"},
    {L"No known nodes yet. Let the daemon complete a walk.", L"Aucun nœud connu. Laissez le démon terminer un parcours.", L"Aún no hay nodos conocidos. Deje que el demonio complete un recorrido.", L"Известных узлов пока нет. Дождитесь завершения обхода.", L"尚无已知节点。请等待守护进程完成遍历。"},
    {L"Node list", L"Liste des nœuds", L"Lista de nodos", L"Список узлов", L"节点列表"},
    {L"Normal mode", L"Mode normal", L"Modo normal", L"Обычный режим", L"普通模式"},
    {L"Normal walking mode", L"Mode de parcours normal", L"Modo de recorrido normal", L"Обычный режим обхода", L"普通遍历模式"},
    {L"Open", L"Ouvrir", L"Abrir", L"Открыть", L"打开"},
    {L"Overview", L"Vue d’ensemble", L"Resumen", L"Обзор", L"概览"},
    {L"Owned DHT", L"DHT possédée", L"DHT propia", L"Собственная DHT", L"自有 DHT"},
    {L"Owner group sizes, comma-separated", L"Tailles des groupes propriétaires, séparées par des virgules", L"Tamaños de grupos propietarios, separados por comas", L"Размеры групп владельцев через запятую", L"所有者组大小，用逗号分隔"},
    {L"Owner groups", L"Groupes propriétaires", L"Grupos propietarios", L"Группы владельцев", L"所有者组"},
    {L"Password", L"Mot de passe", L"Contraseña", L"Пароль", L"密码"},
    {L"Payload", L"Contenu", L"Contenido", L"Данные", L"负载"},
    {L"Peer VLD0 key", L"Clé VLD0 du pair", L"Clave VLD0 del par", L"Ключ VLD0 узла", L"对等节点 VLD0 密钥"},
    {L"Peer handshake", L"Connexion au pair", L"Enlace con par", L"Рукопожатие с узлом", L"对等节点握手"},
    {L"Pending requests", L"Demandes en attente", L"Solicitudes pendientes", L"Ожидающие запросы", L"待处理请求"},
    {L"Published mailbox advertisement (subkey 2)", L"Annonce de boîte aux lettres publiée (sous-clé 2)", L"Anuncio de buzón publicado (subclave 2)", L"Опубликованное объявление почтового ящика (подключ 2)", L"已发布的邮箱公告（子键 2）"},
    {L"Published main/presence header (subkey 0)", L"En-tête principal/de présence publié (sous-clé 0)", L"Encabezado principal/presencia publicado (subclave 0)", L"Опубликованный заголовок присутствия (подключ 0)", L"已发布的主/在线标头（子键 0）"},
    {L"Read", L"Lire", L"Leer", L"Прочитать", L"读取"},
    {L"Read all", L"Tout lire", L"Leer todo", L"Прочитать всё", L"全部读取"},
    {L"Read all external", L"Tout lire (externe)", L"Leer todo externo", L"Прочитать всё внешнее", L"读取全部外部内容"},
    {L"Read selected", L"Lire la sélection", L"Leer selección", L"Прочитать выбранное", L"读取所选"},
    {L"Recent overview log", L"Journal récent de la vue d’ensemble", L"Registro de resumen reciente", L"Последний общий журнал", L"最近概览日志"},
    {L"Recipient", L"Destinataire", L"Destinatario", L"Получатель", L"收件人"},
    {L"Recipient VLD0 key", L"Clé VLD0 du destinataire", L"Clave VLD0 del destinatario", L"Ключ VLD0 получателя", L"收件人 VLD0 密钥"},
    {L"Refresh", L"Actualiser", L"Actualizar", L"Обновить", L"刷新"},
    {L"Refresh both headers", L"Actualiser les deux en-têtes", L"Actualizar ambos encabezados", L"Обновить оба заголовка", L"刷新两个标头"},
    {L"Refresh headers", L"Actualiser les en-têtes", L"Actualizar encabezados", L"Обновить заголовки", L"刷新标头"},
    {L"Register", L"Enregistrer", L"Registrar", L"Зарегистрировать", L"注册"},
    {L"Registration requests", L"Demandes d’enregistrement", L"Solicitudes de registro", L"Запросы регистрации", L"注册请求"},
    {L"Reject", L"Refuser", L"Rechazar", L"Отклонить", L"拒绝"},
    {L"Reject reason", L"Motif du refus", L"Motivo del rechazo", L"Причина отклонения", L"拒绝原因"},
    {L"Rejection reason", L"Motif du refus", L"Motivo del rechazo", L"Причина отклонения", L"拒绝原因"},
    {L"Repair", L"Réparer", L"Reparar", L"Исправить", L"修复"},
    {L"Request id", L"Identifiant de demande", L"Id. de solicitud", L"Номер запроса", L"请求 ID"},
    {L"Retrieve", L"Récupérer", L"Recuperar", L"Получить", L"检索"},
    {L"Retry", L"Réessayer", L"Reintentar", L"Повторить", L"重试"},
    {L"Rotate key", L"Faire tourner la clé", L"Rotar clave", L"Сменить ключ", L"轮换密钥"},
    {L"Rotate selected app key", L"Faire tourner la clé de l’application sélectionnée", L"Rotar clave de la aplicación seleccionada", L"Сменить ключ выбранного приложения", L"轮换所选应用密钥"},
    {L"Route status", L"État des routes", L"Estado de rutas", L"Состояние маршрутов", L"路由状态"},
    {L"Running", L"En cours", L"En ejecución", L"Работает", L"正在运行"},
    {L"Russian", L"Russe", L"Ruso", L"Русский", L"俄语"},
    {L"Save", L"Enregistrer", L"Guardar", L"Сохранить", L"保存"},
    {L"Save DHTs", L"Enregistrer les DHT", L"Guardar DHT", L"Сохранить DHT", L"保存 DHT"},
    {L"Save log", L"Enregistrer le journal", L"Guardar registro", L"Сохранить журнал", L"保存日志"},
    {L"Save owned DHTs", L"Enregistrer les DHT possédées", L"Guardar DHT propias", L"Сохранить собственные DHT", L"保存自有 DHT"},
    {L"Send", L"Envoyer", L"Enviar", L"Отправить", L"发送"},
    {L"Send mail", L"Envoyer le courrier", L"Enviar correo", L"Отправить письмо", L"发送邮件"},
    {L"Send mailbox message", L"Envoyer un message de boîte", L"Enviar mensaje de buzón", L"Отправить почтовое сообщение", L"发送邮箱消息"},
    {L"Show pending requests", L"Afficher les demandes en attente", L"Mostrar solicitudes pendientes", L"Показать ожидающие запросы", L"显示待处理请求"},
    {L"Sign up", L"Créer un compte", L"Crear cuenta", L"Регистрация", L"注册"},
    {L"Single-line value", L"Valeur sur une ligne", L"Valor de una línea", L"Однострочное значение", L"单行值"},
    {L"Spanish", L"Espagnol", L"Español", L"Испанский", L"西班牙语"},
    {L"Start mail walk", L"Démarrer le parcours courrier", L"Iniciar recorrido de correo", L"Запустить почтовый обход", L"开始邮件遍历"},
    {L"Start normal walk", L"Démarrer le parcours normal", L"Iniciar recorrido normal", L"Запустить обычный обход", L"开始普通遍历"},
    {L"Statistics", L"Statistiques", L"Estadísticas", L"Статистика", L"统计"},
    {L"Stats", L"Statistiques", L"Estadísticas", L"Статистика", L"统计"},
    {L"Status", L"État", L"Estado", L"Состояние", L"状态"},
    {L"Stop safely", L"Arrêter proprement", L"Detener con seguridad", L"Безопасно остановить", L"安全停止"},
    {L"Stop walk", L"Arrêter le parcours", L"Detener recorrido", L"Остановить обход", L"停止遍历"},
    {L"Subkey", L"Sous-clé", L"Subclave", L"Подключ", L"子键"},
    {L"Subkey 0 - main/presence header", L"Sous-clé 0 — en-tête principal/de présence", L"Subclave 0: encabezado principal/presencia", L"Подключ 0 — основной заголовок присутствия", L"子键 0 - 主/在线标头"},
    {L"Subkey 2 - mailbox advertisement header", L"Sous-clé 2 — annonce de boîte aux lettres", L"Subclave 2: anuncio de buzón", L"Подключ 2 — объявление почтового ящика", L"子键 2 - 邮箱公告标头"},
    {L"Subkeys", L"Sous-clés", L"Subclaves", L"Подключи", L"子键"},
    {L"Subkeys, e.g. 0,1,10,50-75", L"Sous-clés, ex. 0,1,10,50-75", L"Subclaves, p. ej. 0,1,10,50-75", L"Подключи, напр. 0,1,10,50-75", L"子键，例如 0,1,10,50-75"},
    {L"Target interval (seconds)", L"Intervalle cible (secondes)", L"Intervalo objetivo (segundos)", L"Целевой интервал (секунды)", L"目标间隔（秒）"},
    {L"Target sec", L"Sec. cible", L"Seg. objetivo", L"Цел. сек.", L"目标秒数"},
    {L"The daemon is not ready yet.", L"Le démon n’est pas encore prêt.", L"El demonio aún no está listo.", L"Демон ещё не готов.", L"守护进程尚未就绪。"},
    {L"The foreground service is active.", L"Le service de premier plan est actif.", L"El servicio en primer plano está activo.", L"Фоновая служба активна.", L"前台服务正在运行。"},
    {L"The main key will appear after DHT setup.", L"La clé principale apparaîtra après la configuration DHT.", L"La clave principal aparecerá tras configurar DHT.", L"Основной ключ появится после настройки DHT.", L"DHT 设置完成后将显示主密钥。"},
    {L"Use mail mode for automatic walks", L"Utiliser le mode courrier pour les parcours automatiques", L"Usar modo correo para recorridos automáticos", L"Использовать почтовый режим для автообходов", L"自动遍历使用邮件模式"},
    {L"Username", L"Nom d’utilisateur", L"Nombre de usuario", L"Имя пользователя", L"用户名"},
    {L"Usernames may only contain letters, numbers, underscores, and hyphens.", L"Le nom d’utilisateur ne peut contenir que des lettres, chiffres, traits de soulignement et tirets.", L"El nombre de usuario solo puede contener letras, números, guiones bajos y guiones.", L"Имя пользователя может содержать только буквы, цифры, подчёркивания и дефисы.", L"用户名只能包含字母、数字、下划线和连字符。"},
    {L"Value", L"Valeur", L"Valor", L"Значение", L"值"},
    {L"VeilKnit Daemon Help", L"Aide du démon VeilKnit", L"Ayuda de VeilKnit Daemon", L"Справка демона VeilKnit", L"VeilKnit 守护进程帮助"},
    {L"VeilKnit Mailer", L"Messagerie VeilKnit", L"Correo VeilKnit", L"Почта VeilKnit", L"VeilKnit 邮件"},
    {L"Waiting for the first header read...", L"En attente de la première lecture…", L"Esperando la primera lectura…", L"Ожидание первого чтения…", L"正在等待首次读取…"},
    {L"Walk status", L"État du parcours", L"Estado del recorrido", L"Состояние обхода", L"遍历状态"},
    {L"Write", L"Écrire", L"Escribir", L"Записать", L"写入"},
    {L"Write mail", L"Écrire un message", L"Escribir correo", L"Написать письмо", L"写邮件"},
    {L"Your Mailer inbox is empty.", L"Votre boîte de réception est vide.", L"La bandeja de entrada está vacía.", L"Папка входящих пуста.", L"您的邮件收件箱为空。"},
    {L"Contact", L"Contact", L"Contacto", L"Контакт", L"联系人"},
    {L"Presence", L"Présence", L"Presencia", L"Присутствие", L"在线状态"},
    {L"Verification", L"Vérification", L"Verificación", L"Проверка", L"验证"},
    {L"From", L"De", L"De", L"От", L"发件人"},
    {L"Received", L"Reçu", L"Recibido", L"Получено", L"接收时间"},
    {L"State", L"État", L"Estado", L"Состояние", L"状态"},
    {L"Bytes", L"Octets", L"Bytes", L"Байты", L"字节"},
    {L"Check Mailer approval", L"Vérifier l’approbation de la messagerie", L"Comprobar aprobación del correo", L"Проверить одобрение почты", L"检查邮件应用批准"},
    {L"Reconnect", L"Reconnecter", L"Reconectar", L"Переподключить", L"重新连接"},
    {L"Save nickname", L"Enregistrer le surnom", L"Guardar apodo", L"Сохранить псевдоним", L"保存昵称"},
    {L"Refresh contacts", L"Actualiser les contacts", L"Actualizar contactos", L"Обновить контакты", L"刷新联系人"},
    {L"Find mail", L"Chercher le courrier", L"Buscar correo", L"Найти почту", L"查找邮件"},
    {L"Refresh inbox", L"Actualiser la boîte de réception", L"Actualizar bandeja de entrada", L"Обновить входящие", L"刷新收件箱"},
    {L"Delete selected", L"Supprimer la sélection", L"Eliminar seleccionado", L"Удалить выбранное", L"删除所选"},
    {L"Read", L"Lu", L"Leído", L"Прочитано", L"已读"},
    {L"Unread", L"Non lu", L"No leído", L"Не прочитано", L"未读"},
    {L"known node(s)", L"nœud(s) connu(s)", L"nodo(s) conocido(s)", L"известных узлов", L"个已知节点"},
    {L"unread message(s)", L"message(s) non lu(s)", L"mensaje(s) sin leer", L"непрочитанных сообщений", L"封未读消息"},
    {L"Mailbox retrieval requested", L"Récupération du courrier demandée", L"Recuperación de correo solicitada", L"Запрошено получение почты", L"已请求检索邮件"},
    {L"Mail from", L"Courrier de", L"Correo de", L"Письмо от", L"邮件来自"},
    {L"Delete the selected message?", L"Supprimer le message sélectionné ?", L"¿Eliminar el mensaje seleccionado?", L"Удалить выбранное сообщение?", L"删除所选消息？"},
    {L"Nickname saved", L"Surnom enregistré", L"Apodo guardado", L"Псевдоним сохранён", L"昵称已保存"},
    {L"Select a contact first", L"Sélectionnez d’abord un contact", L"Seleccione primero un contacto", L"Сначала выберите контакт", L"请先选择联系人"},
    {L"Select a recipient", L"Sélectionnez un destinataire", L"Seleccione un destinatario", L"Выберите получателя", L"请选择收件人"},
    {L"Type a message first", L"Saisissez d’abord un message", L"Escriba primero un mensaje", L"Сначала введите сообщение", L"请先输入消息"},
    {L"Mail queued", L"Courrier mis en file", L"Correo en cola", L"Письмо поставлено в очередь", L"邮件已排队"},
    {L"Approve VeilKnit Mailer request", L"Approuvez la demande de messagerie VeilKnit", L"Apruebe la solicitud de VeilKnit Mailer", L"Одобрите запрос VeilKnit Mailer", L"批准 VeilKnit 邮件应用请求"},
    {L"in the daemon", L"dans le démon", L"en el demonio", L"в демоне", L"在守护进程中"},
    {L"Starting…", L"Démarrage…", L"Iniciando…", L"Запуск…", L"正在启动…"},
    {L"Online", L"En ligne", L"En línea", L"В сети", L"在线"},
    {L"Explicitly offline", L"Explicitement hors ligne", L"Explícitamente desconectado", L"Явно не в сети", L"明确离线"},
    {L"Stale online claim", L"Déclaration en ligne périmée", L"Declaración en línea caducada", L"Устаревшее заявление о сети", L"过期在线声明"},
    {L"Needs refresh", L"Actualisation nécessaire", L"Necesita actualización", L"Требуется обновление", L"需要刷新"},
    {L"Unknown", L"Inconnu", L"Desconocido", L"Неизвестно", L"未知"},
    {L"Verified", L"Vérifié", L"Verificado", L"Проверено", L"已验证"},
    {L"Unverified", L"Non vérifié", L"No verificado", L"Не проверено", L"未验证"},
    {L"Set default visible name", L"Définir le nom visible par défaut", L"Establecer nombre visible predeterminado", L"Задать видимое имя по умолчанию", L"设置默认可见名称"},
    {L"Set app alias", L"Définir l’alias de l’application", L"Establecer alias de aplicación", L"Задать псевдоним приложения", L"设置应用别名"},
    {L"Clear alias", L"Effacer l’alias", L"Borrar alias", L"Удалить псевдоним", L"清除别名"},
    {L"List aliases", L"Lister les alias", L"Listar alias", L"Показать псевдонимы", L"列出别名"},
    {L"New profile name", L"Nom du nouveau profil", L"Nombre del nuevo perfil", L"Имя нового профиля", L"新配置文件名称"},
    {L"Profile id", L"Identifiant du profil", L"Id. del perfil", L"Идентификатор профиля", L"配置文件 ID"},
    {L"Create profile", L"Créer le profil", L"Crear perfil", L"Создать профиль", L"创建配置文件"},
    {L"List profiles", L"Lister les profils", L"Listar perfiles", L"Показать профили", L"列出配置文件"},
    {L"Use after restart", L"Utiliser après redémarrage", L"Usar tras reiniciar", L"Использовать после перезапуска", L"重启后使用"},
    {L"Retire profile", L"Retirer le profil", L"Retirar perfil", L"Вывести профиль из использования", L"停用配置文件"},
    };
    if (language == UiLanguage::English || !english) return english;
    for (const auto& row : rows) {
        if (std::wcscmp(row.en, english) == 0) {
            switch (language) {
            case UiLanguage::French: return row.fr;
            case UiLanguage::Spanish: return row.es;
            case UiLanguage::Russian: return row.ru;
            case UiLanguage::Chinese: return row.zh;
            default: return row.en;
            }
        }
    }
    return english;
}
