package com.example.veilknit_mailer

import android.content.Context
import androidx.compose.foundation.layout.Box
import androidx.compose.material3.DropdownMenu
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.Modifier

enum class UiLanguage(val code: String, val nativeName: String) {
    English("en", "English"),
    French("fr", "Français"),
    Spanish("es", "Español"),
    Russian("ru", "Русский"),
    Chinese("zh", "中文");

    companion object {
        fun fromCode(code: String?): UiLanguage = entries.firstOrNull { it.code == code } ?: English
    }
}

object LanguagePreferences {
    private const val FILE = "veilknit_ui"
    private const val KEY = "language"
    fun load(context: Context): UiLanguage = UiLanguage.fromCode(
        context.getSharedPreferences(FILE, Context.MODE_PRIVATE).getString(KEY, "en")
    )
    fun save(context: Context, language: UiLanguage) {
        context.getSharedPreferences(FILE, Context.MODE_PRIVATE).edit().putString(KEY, language.code).apply()
    }
}

private val translations: Map<UiLanguage, Map<String, String>> = mapOf(
        UiLanguage.French to mapOf(
            "Language" to "Langue",
            "English" to "Anglais",
            "French" to "Français",
            "Spanish" to "Espagnol",
            "Russian" to "Russe",
            "Chinese" to "Chinois",
            "Overview" to "Vue d’ensemble",
            "Handshake" to "Poignée de main",
            "Network" to "Réseau",
            "Headers" to "En-têtes",
            "Mailbox" to "Boîte aux lettres",
            "Applications" to "Applications",
            "All logs" to "Tous les journaux",
            "Username" to "Nom d’utilisateur",
            "Password" to "Mot de passe",
            "Log in" to "Se connecter",
            "Create account" to "Créer un compte",
            "Help" to "Aide",
            "Got it" to "Compris",
            "Daemon" to "Démon",
            "Main DHT key" to "Clé DHT principale",
            "Copy key" to "Copier la clé",
            "Save log" to "Enregistrer le journal",
            "Stop safely" to "Arrêter proprement",
            "Recent overview log" to "Journal récent de la vue d’ensemble",
            "Peer handshake" to "Connexion au pair",
            "Peer VLD0 key" to "Clé VLD0 du pair",
            "Establish" to "Établir",
            "Check status" to "Vérifier l’état",
            "Handshake log" to "Journal de connexion",
            "Normal walking mode" to "Mode de parcours normal",
            "Mail walking mode" to "Mode de parcours du courrier",
            "Minimum hops" to "Sauts minimum",
            "Maximum hops" to "Sauts maximum",
            "Minimum interval (seconds)" to "Intervalle minimum (secondes)",
            "Target interval (seconds)" to "Intervalle cible (secondes)",
            "Maximum interval (seconds)" to "Intervalle maximum (secondes)",
            "Use mail mode for automatic walks" to "Utiliser le mode courrier pour les parcours automatiques",
            "Apply and save walk settings" to "Appliquer et enregistrer les paramètres",
            "Start normal walk" to "Démarrer le parcours normal",
            "Start mail walk" to "Démarrer le parcours courrier",
            "Walk status" to "État du parcours",
            "Stop walk" to "Arrêter le parcours",
            "Route status" to "État des routes",
            "Node list" to "Liste des nœuds",
            "Daemon status" to "État du démon",
            "Network log" to "Journal réseau",
            "Published main/presence header (subkey 0)" to "En-tête principal/de présence publié (sous-clé 0)",
            "Copy main header" to "Copier l’en-tête principal",
            "Published mailbox advertisement (subkey 2)" to "Annonce de boîte aux lettres publiée (sous-clé 2)",
            "Copy mailbox header" to "Copier l’en-tête de boîte",
            "Refresh both headers" to "Actualiser les deux en-têtes",
            "Header log" to "Journal d’en-têtes",
            "Create owned DHT" to "Créer une DHT possédée",
            "DHT name" to "Nom de la DHT",
            "Owner group sizes, comma-separated" to "Tailles des groupes propriétaires, séparées par des virgules",
            "Create DHT" to "Créer la DHT",
            "Owned DHT" to "DHT possédée",
            "Index" to "Index",
            "Subkey" to "Sous-clé",
            "Single-line value" to "Valeur sur une ligne",
            "Inspect" to "Inspecter",
            "Write" to "Écrire",
            "Read" to "Lire",
            "Read all" to "Tout lire",
            "Save owned DHTs" to "Enregistrer les DHT possédées",
            "External DHT" to "DHT externe",
            "External VLD0 key" to "Clé VLD0 externe",
            "Subkeys, e.g. 0,1,10,50-75" to "Sous-clés, ex. 0,1,10,50-75",
            "Read selected" to "Lire la sélection",
            "DHT log" to "Journal DHT",
            "Send mailbox message" to "Envoyer un message de boîte",
            "Recipient VLD0 key" to "Clé VLD0 du destinataire",
            "Application id" to "Identifiant d’application",
            "Payload" to "Contenu",
            "Send" to "Envoyer",
            "Status" to "État",
            "List inbox" to "Lister la boîte de réception",
            "Retrieve" to "Récupérer",
            "Stats" to "Statistiques",
            "Flush" to "Vider",
            "Repair" to "Réparer",
            "Mailbox log" to "Journal de boîte aux lettres",
            "Local applications" to "Applications locales",
            "Display name" to "Nom affiché",
            "Register" to "Enregistrer",
            "List" to "Lister",
            "Rotate selected app key" to "Faire tourner la clé de l’application sélectionnée",
            "Registration requests" to "Demandes d’enregistrement",
            "Show pending requests" to "Afficher les demandes en attente",
            "Request id" to "Identifiant de demande",
            "Rejection reason" to "Motif du refus",
            "Approve" to "Approuver",
            "Reject" to "Refuser",
            "Application log" to "Journal d’applications",
            "All daemon logs" to "Tous les journaux du démon",
            "VeilKnit Mailer" to "Messagerie VeilKnit",
            "Contacts" to "Contacts",
            "Inbox" to "Boîte de réception",
            "Compose" to "Rédiger",
            "Close" to "Fermer",
            "Delete" to "Supprimer",
            "Mailer authorization required" to "Autorisation de la messagerie requise",
            "Check approval" to "Vérifier l’approbation",
            "Retry" to "Réessayer",
            "Fresh connect" to "Nouvelle connexion",
            "Connecting to the current daemon account…" to "Connexion au compte actuellement ouvert dans le démon…",
            "Refresh" to "Actualiser",
            "Write mail" to "Écrire un message",
            "Find mail" to "Chercher le courrier",
            "Open" to "Ouvrir",
            "Recipient" to "Destinataire",
            "Message" to "Message",
            "Contact nickname" to "Surnom du contact",
            "Nickname" to "Surnom",
            "Save" to "Enregistrer",
            "Cancel" to "Annuler",
            "No known nodes yet. Let the daemon complete a walk." to "Aucun nœud connu. Laissez le démon terminer un parcours.",
            "Your Mailer inbox is empty." to "Votre boîte de réception est vide.",
            "Network services are ready." to "Les services réseau sont prêts.",
            "The foreground service is active." to "Le service de premier plan est actif.",
            "The main key will appear after DHT setup." to "La clé principale apparaîtra après la configuration DHT.",
            "Android foreground node" to "Nœud Android de premier plan",
            "APP_LINK_HELP" to "Les applications doivent être autorisées par le démon avant de pouvoir utiliser votre identité.\n\nOuvrez Applications et cherchez une ligne comme :\n[api] Application authorization requested: #1 veilknit.rooms\n\nLa valeur importante est le numéro de demande (#1 dans cet exemple). Saisissez 1 dans Identifiant de demande, puis touchez Approuver.\n\nLa page Réseau contient des réglages adaptatifs séparés et des boutons de démarrage pour les parcours normaux et courrier. La page En-têtes affiche vos en-têtes de présence et de boîte aux lettres publiés.\n\nVert signifie prêt, orange signifie démarrage ou reconnexion, et rouge signifie arrêté ou en échec.",
            "Usernames may contain letters, numbers, underscores, and hyphens." to "Le nom d’utilisateur peut contenir des lettres, chiffres, traits de soulignement et tirets.",
            "Enter a password without line breaks." to "Saisissez un mot de passe sans saut de ligne.",
            "Hide password" to "Masquer le mot de passe",
            "Show password" to "Afficher le mot de passe",
            "The password is passed directly to the in-process Rust daemon and is not stored by the Android UI." to "Le mot de passe est transmis directement au démon Rust intégré et n’est pas conservé par l’interface Android.",
            "Native Rust library is not present. Build with cargo-ndk before installing." to "La bibliothèque Rust native est absente. Compilez-la avec cargo-ndk avant l’installation.",
            "Creating account…" to "Création du compte…",
            "Logging in…" to "Connexion…",
            "Main DHT key copied." to "Clé DHT principale copiée.",
            "No log lines to copy yet." to "Aucune ligne de journal à copier pour le moment.",
            "Paste a VLD0: DHT record key first." to "Collez d’abord une clé d’enregistrement DHT VLD0:.",
            "Use whole numbers; minimums must not exceed targets or maximums." to "Utilisez des nombres entiers ; les minimums ne doivent pas dépasser les cibles ou maximums.",
            "Start normal" to "Démarrer normal",
            "Start mail" to "Démarrer courrier",
            "Applied settings are stored in your encrypted daemon account." to "Les paramètres appliqués sont stockés dans votre compte chiffré.",
            "Main header copied." to "En-tête principal copié.",
            "Mailbox header copied." to "En-tête de boîte aux lettres copié.",
            "Enter a name and owner group sizes from 1 to 250." to "Saisissez un nom et des tailles de groupes de 1 à 250.",
            "Enter an index, subkey, and single-line value." to "Saisissez un index, une sous-clé et une valeur sur une ligne.",
            "Enter a VLD0 key and valid subkeys." to "Saisissez une clé VLD0 et des sous-clés valides.",
            "Enter an external VLD0 key." to "Saisissez une clé VLD0 externe.",
            "Enter a recipient key, application id, and single-line payload." to "Saisissez une clé de destinataire, un identifiant d’application et un contenu sur une ligne.",
            "Enter an application id and display name." to "Saisissez un identifiant d’application et un nom affiché.",
            "Enter a numeric request id." to "Saisissez un identifiant de demande numérique.",
            "Enter a request id and single-line reason." to "Saisissez un identifiant de demande et un motif sur une ligne.",
            "No matching log lines yet." to "Aucune ligne de journal correspondante.",
            "Stop daemon safely" to "Arrêter le démon proprement",
            "Connecting to VeilKnit Daemon…" to "Connexion au démon VeilKnit…",
            "Connected" to "Connecté",
            "Authorization required" to "Autorisation requise",
            "known node(s)" to "nœud(s) connu(s)",
            "unread message(s)" to "message(s) non lu(s)",
            "Could not load contacts" to "Impossible de charger les contacts",
            "Could not load inbox" to "Impossible de charger la boîte de réception",
            "Mailbox retrieval requested" to "Récupération du courrier demandée",
            "Message deleted" to "Message supprimé",
            "Select a recipient" to "Sélectionnez un destinataire",
            "Type a message first" to "Saisissez d’abord un message",
            "Mail queued" to "Courrier mis en file",
            "From" to "De",
            "Open VeilKnit Daemon, approve application request" to "Ouvrez le démon VeilKnit et approuvez la demande d’application",
            "then return here." to "puis revenez ici.",
            "Online" to "En ligne",
            "Explicitly offline" to "Explicitement hors ligne",
            "Stale online claim" to "Déclaration en ligne périmée",
            "Needs refresh" to "Actualisation nécessaire",
            "Unknown" to "Inconnu",
            "Verified" to "Vérifié",
            "Unverified" to "Non vérifié"
        ),
        UiLanguage.Spanish to mapOf(
            "Language" to "Idioma",
            "English" to "Inglés",
            "French" to "Francés",
            "Spanish" to "Español",
            "Russian" to "Ruso",
            "Chinese" to "Chino",
            "Overview" to "Resumen",
            "Handshake" to "Enlace",
            "Network" to "Red",
            "Headers" to "Encabezados",
            "Mailbox" to "Buzón",
            "Applications" to "Aplicaciones",
            "All logs" to "Todos los registros",
            "Username" to "Nombre de usuario",
            "Password" to "Contraseña",
            "Log in" to "Iniciar sesión",
            "Create account" to "Crear cuenta",
            "Help" to "Ayuda",
            "Got it" to "Entendido",
            "Daemon" to "Demonio",
            "Main DHT key" to "Clave DHT principal",
            "Copy key" to "Copiar clave",
            "Save log" to "Guardar registro",
            "Stop safely" to "Detener con seguridad",
            "Recent overview log" to "Registro de resumen reciente",
            "Peer handshake" to "Enlace con par",
            "Peer VLD0 key" to "Clave VLD0 del par",
            "Establish" to "Establecer",
            "Check status" to "Comprobar estado",
            "Handshake log" to "Registro de enlace",
            "Normal walking mode" to "Modo de recorrido normal",
            "Mail walking mode" to "Modo de recorrido de correo",
            "Minimum hops" to "Saltos mínimos",
            "Maximum hops" to "Saltos máximos",
            "Minimum interval (seconds)" to "Intervalo mínimo (segundos)",
            "Target interval (seconds)" to "Intervalo objetivo (segundos)",
            "Maximum interval (seconds)" to "Intervalo máximo (segundos)",
            "Use mail mode for automatic walks" to "Usar modo correo para recorridos automáticos",
            "Apply and save walk settings" to "Aplicar y guardar ajustes",
            "Start normal walk" to "Iniciar recorrido normal",
            "Start mail walk" to "Iniciar recorrido de correo",
            "Walk status" to "Estado del recorrido",
            "Stop walk" to "Detener recorrido",
            "Route status" to "Estado de rutas",
            "Node list" to "Lista de nodos",
            "Daemon status" to "Estado del demonio",
            "Network log" to "Registro de red",
            "Published main/presence header (subkey 0)" to "Encabezado principal/presencia publicado (subclave 0)",
            "Copy main header" to "Copiar encabezado principal",
            "Published mailbox advertisement (subkey 2)" to "Anuncio de buzón publicado (subclave 2)",
            "Copy mailbox header" to "Copiar encabezado del buzón",
            "Refresh both headers" to "Actualizar ambos encabezados",
            "Header log" to "Registro de encabezados",
            "Create owned DHT" to "Crear DHT propia",
            "DHT name" to "Nombre de DHT",
            "Owner group sizes, comma-separated" to "Tamaños de grupos propietarios, separados por comas",
            "Create DHT" to "Crear DHT",
            "Owned DHT" to "DHT propia",
            "Index" to "Índice",
            "Subkey" to "Subclave",
            "Single-line value" to "Valor de una línea",
            "Inspect" to "Inspeccionar",
            "Write" to "Escribir",
            "Read" to "Leer",
            "Read all" to "Leer todo",
            "Save owned DHTs" to "Guardar DHT propias",
            "External DHT" to "DHT externa",
            "External VLD0 key" to "Clave VLD0 externa",
            "Subkeys, e.g. 0,1,10,50-75" to "Subclaves, p. ej. 0,1,10,50-75",
            "Read selected" to "Leer selección",
            "DHT log" to "Registro DHT",
            "Send mailbox message" to "Enviar mensaje de buzón",
            "Recipient VLD0 key" to "Clave VLD0 del destinatario",
            "Application id" to "Id. de aplicación",
            "Payload" to "Contenido",
            "Send" to "Enviar",
            "Status" to "Estado",
            "List inbox" to "Listar bandeja de entrada",
            "Retrieve" to "Recuperar",
            "Stats" to "Estadísticas",
            "Flush" to "Vaciar",
            "Repair" to "Reparar",
            "Mailbox log" to "Registro del buzón",
            "Local applications" to "Aplicaciones locales",
            "Display name" to "Nombre mostrado",
            "Register" to "Registrar",
            "List" to "Listar",
            "Rotate selected app key" to "Rotar clave de la aplicación seleccionada",
            "Registration requests" to "Solicitudes de registro",
            "Show pending requests" to "Mostrar solicitudes pendientes",
            "Request id" to "Id. de solicitud",
            "Rejection reason" to "Motivo del rechazo",
            "Approve" to "Aprobar",
            "Reject" to "Rechazar",
            "Application log" to "Registro de aplicaciones",
            "All daemon logs" to "Todos los registros del demonio",
            "VeilKnit Mailer" to "Correo VeilKnit",
            "Contacts" to "Contactos",
            "Inbox" to "Bandeja de entrada",
            "Compose" to "Redactar",
            "Close" to "Cerrar",
            "Delete" to "Eliminar",
            "Mailer authorization required" to "Se requiere autorización del correo",
            "Check approval" to "Comprobar aprobación",
            "Retry" to "Reintentar",
            "Fresh connect" to "Conexión nueva",
            "Connecting to the current daemon account…" to "Conectando con la cuenta abierta actualmente en el demonio…",
            "Refresh" to "Actualizar",
            "Write mail" to "Escribir correo",
            "Find mail" to "Buscar correo",
            "Open" to "Abrir",
            "Recipient" to "Destinatario",
            "Message" to "Mensaje",
            "Contact nickname" to "Apodo del contacto",
            "Nickname" to "Apodo",
            "Save" to "Guardar",
            "Cancel" to "Cancelar",
            "No known nodes yet. Let the daemon complete a walk." to "Aún no hay nodos conocidos. Deje que el demonio complete un recorrido.",
            "Your Mailer inbox is empty." to "La bandeja de entrada está vacía.",
            "Network services are ready." to "Los servicios de red están listos.",
            "The foreground service is active." to "El servicio en primer plano está activo.",
            "The main key will appear after DHT setup." to "La clave principal aparecerá tras configurar DHT.",
            "Android foreground node" to "Nodo Android en primer plano",
            "APP_LINK_HELP" to "Las aplicaciones deben pedir autorización al demonio antes de usar su identidad.\n\nAbra Aplicaciones y busque una línea como:\n[api] Application authorization requested: #1 veilknit.rooms\n\nEl valor importante es el número de solicitud (#1 en este ejemplo). Escriba 1 en Id. de solicitud y pulse Aprobar.\n\nLa página Red contiene ajustes adaptativos separados y botones para iniciar recorridos normales y de correo. La página Encabezados muestra los encabezados publicados de presencia y buzón.\n\nVerde significa listo, naranja significa iniciando o reconectando y rojo significa detenido o con error.",
            "Usernames may contain letters, numbers, underscores, and hyphens." to "El nombre de usuario puede contener letras, números, guiones bajos y guiones.",
            "Enter a password without line breaks." to "Introduzca una contraseña sin saltos de línea.",
            "Hide password" to "Ocultar contraseña",
            "Show password" to "Mostrar contraseña",
            "The password is passed directly to the in-process Rust daemon and is not stored by the Android UI." to "La contraseña se pasa directamente al demonio Rust del proceso y la interfaz Android no la guarda.",
            "Native Rust library is not present. Build with cargo-ndk before installing." to "Falta la biblioteca Rust nativa. Compílela con cargo-ndk antes de instalar.",
            "Creating account…" to "Creando cuenta…",
            "Logging in…" to "Iniciando sesión…",
            "Main DHT key copied." to "Clave DHT principal copiada.",
            "No log lines to copy yet." to "Aún no hay líneas de registro para copiar.",
            "Paste a VLD0: DHT record key first." to "Pegue primero una clave de registro DHT VLD0:.",
            "Use whole numbers; minimums must not exceed targets or maximums." to "Use números enteros; los mínimos no deben superar los objetivos o máximos.",
            "Start normal" to "Iniciar normal",
            "Start mail" to "Iniciar correo",
            "Applied settings are stored in your encrypted daemon account." to "Los ajustes aplicados se guardan en su cuenta cifrada.",
            "Main header copied." to "Encabezado principal copiado.",
            "Mailbox header copied." to "Encabezado del buzón copiado.",
            "Enter a name and owner group sizes from 1 to 250." to "Introduzca un nombre y tamaños de grupo de 1 a 250.",
            "Enter an index, subkey, and single-line value." to "Introduzca un índice, subclave y valor de una línea.",
            "Enter a VLD0 key and valid subkeys." to "Introduzca una clave VLD0 y subclaves válidas.",
            "Enter an external VLD0 key." to "Introduzca una clave VLD0 externa.",
            "Enter a recipient key, application id, and single-line payload." to "Introduzca una clave de destinatario, id. de aplicación y contenido de una línea.",
            "Enter an application id and display name." to "Introduzca un id. de aplicación y nombre mostrado.",
            "Enter a numeric request id." to "Introduzca un id. de solicitud numérico.",
            "Enter a request id and single-line reason." to "Introduzca un id. de solicitud y motivo de una línea.",
            "No matching log lines yet." to "Aún no hay líneas de registro coincidentes.",
            "Stop daemon safely" to "Detener el demonio con seguridad",
            "Connecting to VeilKnit Daemon…" to "Conectando con VeilKnit Daemon…",
            "Connected" to "Conectado",
            "Authorization required" to "Se requiere autorización",
            "known node(s)" to "nodo(s) conocido(s)",
            "unread message(s)" to "mensaje(s) sin leer",
            "Could not load contacts" to "No se pudieron cargar los contactos",
            "Could not load inbox" to "No se pudo cargar la bandeja de entrada",
            "Mailbox retrieval requested" to "Recuperación de correo solicitada",
            "Message deleted" to "Mensaje eliminado",
            "Select a recipient" to "Seleccione un destinatario",
            "Type a message first" to "Escriba primero un mensaje",
            "Mail queued" to "Correo en cola",
            "From" to "De",
            "Open VeilKnit Daemon, approve application request" to "Abra VeilKnit Daemon y apruebe la solicitud de aplicación",
            "then return here." to "después vuelva aquí.",
            "Online" to "En línea",
            "Explicitly offline" to "Explícitamente desconectado",
            "Stale online claim" to "Declaración en línea caducada",
            "Needs refresh" to "Necesita actualización",
            "Unknown" to "Desconocido",
            "Verified" to "Verificado",
            "Unverified" to "No verificado"
        ),
        UiLanguage.Russian to mapOf(
            "Language" to "Язык",
            "English" to "Английский",
            "French" to "Французский",
            "Spanish" to "Испанский",
            "Russian" to "Русский",
            "Chinese" to "Китайский",
            "Overview" to "Обзор",
            "Handshake" to "Рукопожатие",
            "Network" to "Сеть",
            "Headers" to "Заголовки",
            "Mailbox" to "Почтовый ящик",
            "Applications" to "Приложения",
            "All logs" to "Все журналы",
            "Username" to "Имя пользователя",
            "Password" to "Пароль",
            "Log in" to "Войти",
            "Create account" to "Создать учётную запись",
            "Help" to "Справка",
            "Got it" to "Понятно",
            "Daemon" to "Демон",
            "Main DHT key" to "Основной ключ DHT",
            "Copy key" to "Копировать ключ",
            "Save log" to "Сохранить журнал",
            "Stop safely" to "Безопасно остановить",
            "Recent overview log" to "Последний общий журнал",
            "Peer handshake" to "Рукопожатие с узлом",
            "Peer VLD0 key" to "Ключ VLD0 узла",
            "Establish" to "Установить",
            "Check status" to "Проверить состояние",
            "Handshake log" to "Журнал рукопожатия",
            "Normal walking mode" to "Обычный режим обхода",
            "Mail walking mode" to "Почтовый режим обхода",
            "Minimum hops" to "Минимум переходов",
            "Maximum hops" to "Максимум переходов",
            "Minimum interval (seconds)" to "Минимальный интервал (секунды)",
            "Target interval (seconds)" to "Целевой интервал (секунды)",
            "Maximum interval (seconds)" to "Максимальный интервал (секунды)",
            "Use mail mode for automatic walks" to "Использовать почтовый режим для автообходов",
            "Apply and save walk settings" to "Применить и сохранить настройки",
            "Start normal walk" to "Запустить обычный обход",
            "Start mail walk" to "Запустить почтовый обход",
            "Walk status" to "Состояние обхода",
            "Stop walk" to "Остановить обход",
            "Route status" to "Состояние маршрутов",
            "Node list" to "Список узлов",
            "Daemon status" to "Состояние демона",
            "Network log" to "Сетевой журнал",
            "Published main/presence header (subkey 0)" to "Опубликованный заголовок присутствия (подключ 0)",
            "Copy main header" to "Копировать основной заголовок",
            "Published mailbox advertisement (subkey 2)" to "Опубликованное объявление почтового ящика (подключ 2)",
            "Copy mailbox header" to "Копировать заголовок почты",
            "Refresh both headers" to "Обновить оба заголовка",
            "Header log" to "Журнал заголовков",
            "Create owned DHT" to "Создать собственную DHT",
            "DHT name" to "Имя DHT",
            "Owner group sizes, comma-separated" to "Размеры групп владельцев через запятую",
            "Create DHT" to "Создать DHT",
            "Owned DHT" to "Собственная DHT",
            "Index" to "Индекс",
            "Subkey" to "Подключ",
            "Single-line value" to "Однострочное значение",
            "Inspect" to "Проверить",
            "Write" to "Записать",
            "Read" to "Прочитать",
            "Read all" to "Прочитать всё",
            "Save owned DHTs" to "Сохранить собственные DHT",
            "External DHT" to "Внешняя DHT",
            "External VLD0 key" to "Внешний ключ VLD0",
            "Subkeys, e.g. 0,1,10,50-75" to "Подключи, напр. 0,1,10,50-75",
            "Read selected" to "Прочитать выбранное",
            "DHT log" to "Журнал DHT",
            "Send mailbox message" to "Отправить почтовое сообщение",
            "Recipient VLD0 key" to "Ключ VLD0 получателя",
            "Application id" to "Идентификатор приложения",
            "Payload" to "Данные",
            "Send" to "Отправить",
            "Status" to "Состояние",
            "List inbox" to "Показать входящие",
            "Retrieve" to "Получить",
            "Stats" to "Статистика",
            "Flush" to "Сбросить",
            "Repair" to "Исправить",
            "Mailbox log" to "Почтовый журнал",
            "Local applications" to "Локальные приложения",
            "Display name" to "Отображаемое имя",
            "Register" to "Зарегистрировать",
            "List" to "Список",
            "Rotate selected app key" to "Сменить ключ выбранного приложения",
            "Registration requests" to "Запросы регистрации",
            "Show pending requests" to "Показать ожидающие запросы",
            "Request id" to "Номер запроса",
            "Rejection reason" to "Причина отклонения",
            "Approve" to "Одобрить",
            "Reject" to "Отклонить",
            "Application log" to "Журнал приложений",
            "All daemon logs" to "Все журналы демона",
            "VeilKnit Mailer" to "Почта VeilKnit",
            "Contacts" to "Контакты",
            "Inbox" to "Входящие",
            "Compose" to "Написать",
            "Close" to "Закрыть",
            "Delete" to "Удалить",
            "Mailer authorization required" to "Требуется авторизация почты",
            "Check approval" to "Проверить одобрение",
            "Retry" to "Повторить",
            "Fresh connect" to "Новое подключение",
            "Connecting to the current daemon account…" to "Подключение к учётной записи, открытой сейчас в демоне…",
            "Refresh" to "Обновить",
            "Write mail" to "Написать письмо",
            "Find mail" to "Найти почту",
            "Open" to "Открыть",
            "Recipient" to "Получатель",
            "Message" to "Сообщение",
            "Contact nickname" to "Псевдоним контакта",
            "Nickname" to "Псевдоним",
            "Save" to "Сохранить",
            "Cancel" to "Отмена",
            "No known nodes yet. Let the daemon complete a walk." to "Известных узлов пока нет. Дождитесь завершения обхода.",
            "Your Mailer inbox is empty." to "Папка входящих пуста.",
            "Network services are ready." to "Сетевые службы готовы.",
            "The foreground service is active." to "Фоновая служба активна.",
            "The main key will appear after DHT setup." to "Основной ключ появится после настройки DHT.",
            "Android foreground node" to "Фоновый узел Android",
            "APP_LINK_HELP" to "Приложения должны получить разрешение демона, прежде чем использовать вашу личность.\n\nОткройте раздел Приложения и найдите строку вида:\n[api] Application authorization requested: #1 veilknit.rooms\n\nВажное значение — номер запроса (#1 в примере). Введите 1 в поле Номер запроса и нажмите Одобрить.\n\nНа странице Сеть находятся отдельные адаптивные настройки и кнопки запуска обычного и почтового обхода. На странице Заголовки показаны опубликованные заголовки присутствия и почтового ящика.\n\nЗелёный означает готовность, оранжевый — запуск или переподключение, красный — остановку или ошибку.",
            "Usernames may contain letters, numbers, underscores, and hyphens." to "Имя пользователя может содержать буквы, цифры, подчёркивания и дефисы.",
            "Enter a password without line breaks." to "Введите пароль без переносов строк.",
            "Hide password" to "Скрыть пароль",
            "Show password" to "Показать пароль",
            "The password is passed directly to the in-process Rust daemon and is not stored by the Android UI." to "Пароль передаётся напрямую встроенному демону Rust и не сохраняется интерфейсом Android.",
            "Native Rust library is not present. Build with cargo-ndk before installing." to "Нативная библиотека Rust отсутствует. Соберите её с cargo-ndk перед установкой.",
            "Creating account…" to "Создание учётной записи…",
            "Logging in…" to "Вход…",
            "Main DHT key copied." to "Основной ключ DHT скопирован.",
            "No log lines to copy yet." to "Строк журнала для копирования пока нет.",
            "Paste a VLD0: DHT record key first." to "Сначала вставьте ключ записи DHT VLD0:.",
            "Use whole numbers; minimums must not exceed targets or maximums." to "Используйте целые числа; минимумы не должны превышать целевые или максимальные значения.",
            "Start normal" to "Обычный обход",
            "Start mail" to "Почтовый обход",
            "Applied settings are stored in your encrypted daemon account." to "Применённые настройки хранятся в зашифрованной учётной записи.",
            "Main header copied." to "Основной заголовок скопирован.",
            "Mailbox header copied." to "Почтовый заголовок скопирован.",
            "Enter a name and owner group sizes from 1 to 250." to "Введите имя и размеры групп от 1 до 250.",
            "Enter an index, subkey, and single-line value." to "Введите индекс, подключ и однострочное значение.",
            "Enter a VLD0 key and valid subkeys." to "Введите ключ VLD0 и допустимые подключи.",
            "Enter an external VLD0 key." to "Введите внешний ключ VLD0.",
            "Enter a recipient key, application id, and single-line payload." to "Введите ключ получателя, идентификатор приложения и однострочные данные.",
            "Enter an application id and display name." to "Введите идентификатор приложения и отображаемое имя.",
            "Enter a numeric request id." to "Введите числовой номер запроса.",
            "Enter a request id and single-line reason." to "Введите номер запроса и однострочную причину.",
            "No matching log lines yet." to "Подходящих строк журнала пока нет.",
            "Stop daemon safely" to "Безопасно остановить демон",
            "Connecting to VeilKnit Daemon…" to "Подключение к демону VeilKnit…",
            "Connected" to "Подключено",
            "Authorization required" to "Требуется авторизация",
            "known node(s)" to "известных узлов",
            "unread message(s)" to "непрочитанных сообщений",
            "Could not load contacts" to "Не удалось загрузить контакты",
            "Could not load inbox" to "Не удалось загрузить входящие",
            "Mailbox retrieval requested" to "Запрошено получение почты",
            "Message deleted" to "Сообщение удалено",
            "Select a recipient" to "Выберите получателя",
            "Type a message first" to "Сначала введите сообщение",
            "Mail queued" to "Письмо поставлено в очередь",
            "From" to "От",
            "Open VeilKnit Daemon, approve application request" to "Откройте демон VeilKnit и одобрите запрос приложения",
            "then return here." to "затем вернитесь сюда.",
            "Online" to "В сети",
            "Explicitly offline" to "Явно не в сети",
            "Stale online claim" to "Устаревшее заявление о сети",
            "Needs refresh" to "Требуется обновление",
            "Unknown" to "Неизвестно",
            "Verified" to "Проверено",
            "Unverified" to "Не проверено"
        ),
        UiLanguage.Chinese to mapOf(
            "Language" to "语言",
            "English" to "英语",
            "French" to "法语",
            "Spanish" to "西班牙语",
            "Russian" to "俄语",
            "Chinese" to "中文",
            "Overview" to "概览",
            "Handshake" to "握手",
            "Network" to "网络",
            "Headers" to "标头",
            "Mailbox" to "邮箱",
            "Applications" to "应用程序",
            "All logs" to "所有日志",
            "Username" to "用户名",
            "Password" to "密码",
            "Log in" to "登录",
            "Create account" to "创建账户",
            "Help" to "帮助",
            "Got it" to "知道了",
            "Daemon" to "守护进程",
            "Main DHT key" to "主 DHT 密钥",
            "Copy key" to "复制密钥",
            "Save log" to "保存日志",
            "Stop safely" to "安全停止",
            "Recent overview log" to "最近概览日志",
            "Peer handshake" to "对等节点握手",
            "Peer VLD0 key" to "对等节点 VLD0 密钥",
            "Establish" to "建立",
            "Check status" to "检查状态",
            "Handshake log" to "握手日志",
            "Normal walking mode" to "普通遍历模式",
            "Mail walking mode" to "邮件遍历模式",
            "Minimum hops" to "最少跳数",
            "Maximum hops" to "最大跳数",
            "Minimum interval (seconds)" to "最小间隔（秒）",
            "Target interval (seconds)" to "目标间隔（秒）",
            "Maximum interval (seconds)" to "最大间隔（秒）",
            "Use mail mode for automatic walks" to "自动遍历使用邮件模式",
            "Apply and save walk settings" to "应用并保存遍历设置",
            "Start normal walk" to "开始普通遍历",
            "Start mail walk" to "开始邮件遍历",
            "Walk status" to "遍历状态",
            "Stop walk" to "停止遍历",
            "Route status" to "路由状态",
            "Node list" to "节点列表",
            "Daemon status" to "守护进程状态",
            "Network log" to "网络日志",
            "Published main/presence header (subkey 0)" to "已发布的主/在线标头（子键 0）",
            "Copy main header" to "复制主标头",
            "Published mailbox advertisement (subkey 2)" to "已发布的邮箱公告（子键 2）",
            "Copy mailbox header" to "复制邮箱标头",
            "Refresh both headers" to "刷新两个标头",
            "Header log" to "标头日志",
            "Create owned DHT" to "创建自有 DHT",
            "DHT name" to "DHT 名称",
            "Owner group sizes, comma-separated" to "所有者组大小，用逗号分隔",
            "Create DHT" to "创建 DHT",
            "Owned DHT" to "自有 DHT",
            "Index" to "索引",
            "Subkey" to "子键",
            "Single-line value" to "单行值",
            "Inspect" to "检查",
            "Write" to "写入",
            "Read" to "读取",
            "Read all" to "全部读取",
            "Save owned DHTs" to "保存自有 DHT",
            "External DHT" to "外部 DHT",
            "External VLD0 key" to "外部 VLD0 密钥",
            "Subkeys, e.g. 0,1,10,50-75" to "子键，例如 0,1,10,50-75",
            "Read selected" to "读取所选",
            "DHT log" to "DHT 日志",
            "Send mailbox message" to "发送邮箱消息",
            "Recipient VLD0 key" to "收件人 VLD0 密钥",
            "Application id" to "应用程序 ID",
            "Payload" to "负载",
            "Send" to "发送",
            "Status" to "状态",
            "List inbox" to "列出收件箱",
            "Retrieve" to "检索",
            "Stats" to "统计",
            "Flush" to "清空",
            "Repair" to "修复",
            "Mailbox log" to "邮箱日志",
            "Local applications" to "本地应用程序",
            "Display name" to "显示名称",
            "Register" to "注册",
            "List" to "列表",
            "Rotate selected app key" to "轮换所选应用密钥",
            "Registration requests" to "注册请求",
            "Show pending requests" to "显示待处理请求",
            "Request id" to "请求 ID",
            "Rejection reason" to "拒绝原因",
            "Approve" to "批准",
            "Reject" to "拒绝",
            "Application log" to "应用程序日志",
            "All daemon logs" to "所有守护进程日志",
            "VeilKnit Mailer" to "VeilKnit 邮件",
            "Contacts" to "联系人",
            "Inbox" to "收件箱",
            "Compose" to "撰写",
            "Close" to "关闭",
            "Delete" to "删除",
            "Mailer authorization required" to "需要邮件应用授权",
            "Check approval" to "检查批准",
            "Retry" to "重试",
            "Fresh connect" to "全新连接",
            "Connecting to the current daemon account…" to "正在连接守护进程中当前登录的账户…",
            "Refresh" to "刷新",
            "Write mail" to "写邮件",
            "Find mail" to "查找邮件",
            "Open" to "打开",
            "Recipient" to "收件人",
            "Message" to "消息",
            "Contact nickname" to "联系人昵称",
            "Nickname" to "昵称",
            "Save" to "保存",
            "Cancel" to "取消",
            "No known nodes yet. Let the daemon complete a walk." to "尚无已知节点。请等待守护进程完成遍历。",
            "Your Mailer inbox is empty." to "您的邮件收件箱为空。",
            "Network services are ready." to "网络服务已就绪。",
            "The foreground service is active." to "前台服务正在运行。",
            "The main key will appear after DHT setup." to "DHT 设置完成后将显示主密钥。",
            "Android foreground node" to "Android 前台节点",
            "APP_LINK_HELP" to "应用程序必须先获得守护进程授权，才能使用您的身份。\n\n打开“应用程序”，查找类似以下内容的行：\n[api] Application authorization requested: #1 veilknit.rooms\n\n重要的是请求编号（本例中为 #1）。在“请求 ID”中输入 1，然后点击“批准”。\n\n“网络”页面为普通遍历和邮件遍历提供独立的自适应设置与启动按钮。“标头”页面显示已发布的在线状态和邮箱公告标头。\n\n绿色表示已就绪，橙色表示正在启动或重新连接，红色表示已停止或失败。",
            "Usernames may contain letters, numbers, underscores, and hyphens." to "用户名可包含字母、数字、下划线和连字符。",
            "Enter a password without line breaks." to "请输入不含换行符的密码。",
            "Hide password" to "隐藏密码",
            "Show password" to "显示密码",
            "The password is passed directly to the in-process Rust daemon and is not stored by the Android UI." to "密码会直接传给进程内的 Rust 守护进程，Android 界面不会保存密码。",
            "Native Rust library is not present. Build with cargo-ndk before installing." to "缺少原生 Rust 库。请先使用 cargo-ndk 构建再安装。",
            "Creating account…" to "正在创建账户…",
            "Logging in…" to "正在登录…",
            "Main DHT key copied." to "主 DHT 密钥已复制。",
            "No log lines to copy yet." to "暂时没有可复制的日志行。",
            "Paste a VLD0: DHT record key first." to "请先粘贴 VLD0: DHT 记录密钥。",
            "Use whole numbers; minimums must not exceed targets or maximums." to "请使用整数；最小值不得超过目标值或最大值。",
            "Start normal" to "开始普通遍历",
            "Start mail" to "开始邮件遍历",
            "Applied settings are stored in your encrypted daemon account." to "应用的设置会存储在加密的守护进程账户中。",
            "Main header copied." to "主标头已复制。",
            "Mailbox header copied." to "邮箱标头已复制。",
            "Enter a name and owner group sizes from 1 to 250." to "请输入名称以及 1 到 250 的所有者组大小。",
            "Enter an index, subkey, and single-line value." to "请输入索引、子键和单行值。",
            "Enter a VLD0 key and valid subkeys." to "请输入 VLD0 密钥和有效子键。",
            "Enter an external VLD0 key." to "请输入外部 VLD0 密钥。",
            "Enter a recipient key, application id, and single-line payload." to "请输入收件人密钥、应用程序 ID 和单行负载。",
            "Enter an application id and display name." to "请输入应用程序 ID 和显示名称。",
            "Enter a numeric request id." to "请输入数字请求 ID。",
            "Enter a request id and single-line reason." to "请输入请求 ID 和单行原因。",
            "No matching log lines yet." to "暂时没有匹配的日志行。",
            "Stop daemon safely" to "安全停止守护进程",
            "Connecting to VeilKnit Daemon…" to "正在连接 VeilKnit 守护进程…",
            "Connected" to "已连接",
            "Authorization required" to "需要授权",
            "known node(s)" to "个已知节点",
            "unread message(s)" to "封未读消息",
            "Could not load contacts" to "无法加载联系人",
            "Could not load inbox" to "无法加载收件箱",
            "Mailbox retrieval requested" to "已请求检索邮件",
            "Message deleted" to "消息已删除",
            "Select a recipient" to "请选择收件人",
            "Type a message first" to "请先输入消息",
            "Mail queued" to "邮件已排队",
            "From" to "发件人",
            "Open VeilKnit Daemon, approve application request" to "打开 VeilKnit 守护进程并批准应用请求",
            "then return here." to "然后返回此处。",
            "Online" to "在线",
            "Explicitly offline" to "明确离线",
            "Stale online claim" to "过期在线声明",
            "Needs refresh" to "需要刷新",
            "Unknown" to "未知",
            "Verified" to "已验证",
            "Unverified" to "未验证"
        )
)


private fun commonTranslation(language: UiLanguage, english: String): String? = when (language) {
    UiLanguage.English -> null
    UiLanguage.French -> when (english) {
        "DHT" -> "DHT"
        "Stopped" -> "Arrêté"
        "Starting…" -> "Démarrage…"
        "Running" -> "En cours"
        "Authenticated; starting network services…" -> "Authentifié ; démarrage des services réseau…"
        "Authentication failed" -> "Échec de l’authentification"
        "Error" -> "Erreur"
        "Waiting for the first header read…" -> "En attente de la première lecture d’en-tête…"
        "Log saved; last lines copied." -> "Journal enregistré ; dernières lignes copiées."
        else -> null
    }
    UiLanguage.Spanish -> when (english) {
        "DHT" -> "DHT"
        "Stopped" -> "Detenido"
        "Starting…" -> "Iniciando…"
        "Running" -> "En ejecución"
        "Authenticated; starting network services…" -> "Autenticado; iniciando servicios de red…"
        "Authentication failed" -> "Error de autenticación"
        "Error" -> "Error"
        "Waiting for the first header read…" -> "Esperando la primera lectura de encabezado…"
        "Log saved; last lines copied." -> "Registro guardado; últimas líneas copiadas."
        else -> null
    }
    UiLanguage.Russian -> when (english) {
        "DHT" -> "DHT"
        "Stopped" -> "Остановлен"
        "Starting…" -> "Запуск…"
        "Running" -> "Работает"
        "Authenticated; starting network services…" -> "Вход выполнен; запуск сетевых служб…"
        "Authentication failed" -> "Ошибка входа"
        "Error" -> "Ошибка"
        "Waiting for the first header read…" -> "Ожидание первого чтения заголовка…"
        "Log saved; last lines copied." -> "Журнал сохранён; последние строки скопированы."
        else -> null
    }
    UiLanguage.Chinese -> when (english) {
        "DHT" -> "DHT"
        "Stopped" -> "已停止"
        "Starting…" -> "正在启动…"
        "Running" -> "运行中"
        "Authenticated; starting network services…" -> "已认证；正在启动网络服务…"
        "Authentication failed" -> "认证失败"
        "Error" -> "错误"
        "Waiting for the first header read…" -> "等待第一次读取标头…"
        "Log saved; last lines copied." -> "日志已保存；已复制最后的日志行。"
        else -> null
    }
}

val LocalUiLanguage = staticCompositionLocalOf { UiLanguage.English }

object UiStrings {
    @Volatile var current: UiLanguage = UiLanguage.English
}

fun localized(language: UiLanguage, english: String): String =
    translations[language]?.get(english) ?: commonTranslation(language, english) ?: english

fun tr(english: String): String = localized(UiStrings.current, english)

@Composable
fun LanguageSelector(
    language: UiLanguage,
    onLanguageChange: (UiLanguage) -> Unit,
    modifier: Modifier = Modifier,
) {
    var expanded by remember { mutableStateOf(false) }
    Box(modifier) {
        TextButton(onClick = { expanded = true }) {
            Text("${localized(language, "Language")}: ${language.nativeName}")
        }
        DropdownMenu(expanded = expanded, onDismissRequest = { expanded = false }) {
            UiLanguage.entries.forEach { option ->
                DropdownMenuItem(
                    text = { Text(option.nativeName) },
                    onClick = { expanded = false; onLanguageChange(option) },
                )
            }
        }
    }
}
